"""phase 5d: engagement nudges

Revision ID: 0008
Revises: 0007
Create Date: 2026-04-22 00:00:00.000000

Tables created:
    - pending_confirmations: persistent audit of every bot proposal so the
      stale_pending_confirmation evaluator can find proposals older than 48h.
      Redis still owns live-session state (TTL 5m); this table is the
      durable mirror that survives restarts and long silences.
    - user_nudges: the nudge itself — generated by an evaluator, delivered
      (or not) by the delivery worker. Status transitions:
      pending → sent|suppressed|expired; sent → dismissed|acted_on.
    - user_nudge_silences: per-user, per-type silence windows. Inserted when
      the user dismisses the same nudge_type twice within 30 days.

No seeds. Evaluators populate user_nudges at runtime; silences are derived
from user actions.

Rollback: drops all three tables in reverse order. No data is preserved —
nudges are cheap to regenerate.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "0008"
down_revision: Union[str, None] = "0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── pending_confirmations ────────────────────────────────────────────────
    # Durable mirror of every PendingAction stored in Redis. Written on
    # ProposeAction, updated on resolution. The evaluator reads
    # `resolved_at IS NULL AND created_at <= now() - 48h`.
    op.create_table(
        "pending_confirmations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("short_id", sa.String(16), nullable=False),
        sa.Column(
            "channel", sa.String(20), nullable=False, server_default="telegram"
        ),
        sa.Column("channel_message_id", sa.String(64), nullable=True),
        sa.Column("action_type", sa.String(32), nullable=False),
        sa.Column("proposed_action", postgresql.JSONB(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(resolved_at IS NULL) = (resolution IS NULL)",
            name="ck_pending_confirmations_resolution_consistency",
        ),
        sa.CheckConstraint(
            "resolution IS NULL OR resolution IN "
            "('confirmed','rejected','edited','superseded','cancelled')",
            name="ck_pending_confirmations_resolution_values",
        ),
    )
    # Partial index is the hot path: "unresolved proposals older than N hours
    # for a given user". Keeping it partial means it only indexes the rows
    # the evaluator actually scans.
    op.create_index(
        "ix_pending_confirmations_unresolved",
        "pending_confirmations",
        ["user_id", "created_at"],
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_index(
        "ix_pending_confirmations_user_created",
        "pending_confirmations",
        ["user_id", sa.text("created_at DESC")],
    )

    # ── user_nudges ──────────────────────────────────────────────────────────
    op.create_table(
        "user_nudges",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("nudge_type", sa.String(40), nullable=False),
        sa.Column(
            "priority", sa.String(10), nullable=False, server_default="normal"
        ),
        sa.Column("dedup_key", sa.String(255), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "source_notification_event_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "status", sa.String(20), nullable=False, server_default="pending"
        ),
        sa.Column("delivery_channel", sa.String(20), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("sent_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("dismissed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("acted_on_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expired_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        # ON DELETE SET NULL lets us keep the nudge audit even if the
        # underlying notification_event gets cascaded away.
        sa.ForeignKeyConstraint(
            ["source_notification_event_id"],
            ["notification_events.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "nudge_type IN "
            "('missing_income','stale_pending_confirmation','upcoming_bill')",
            name="ck_user_nudges_nudge_type",
        ),
        sa.CheckConstraint(
            "priority IN ('normal','high')",
            name="ck_user_nudges_priority",
        ),
        sa.CheckConstraint(
            "status IN "
            "('pending','sent','dismissed','acted_on','expired','suppressed')",
            name="ck_user_nudges_status",
        ),
        # Dedup guarantee: the evaluator uses ON CONFLICT DO NOTHING against
        # this constraint so re-running the job is a no-op.
        sa.UniqueConstraint(
            "user_id", "dedup_key", name="uq_user_nudges_user_dedup"
        ),
    )
    op.create_index(
        "ix_user_nudges_user_status_created",
        "user_nudges",
        ["user_id", "status", sa.text("created_at DESC")],
    )
    # Partial index for the delivery worker — it only scans pending rows.
    op.create_index(
        "ix_user_nudges_pending",
        "user_nudges",
        ["created_at"],
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ix_user_nudges_source_notification_event",
        "user_nudges",
        ["source_notification_event_id"],
    )

    # ── user_nudge_silences ──────────────────────────────────────────────────
    op.create_table(
        "user_nudge_silences",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("nudge_type", sa.String(40), nullable=False),
        sa.Column(
            "silenced_until", sa.TIMESTAMP(timezone=True), nullable=False
        ),
        sa.Column("reason", sa.String(64), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "nudge_type IN "
            "('missing_income','stale_pending_confirmation','upcoming_bill')",
            name="ck_user_nudge_silences_nudge_type",
        ),
    )
    op.create_index(
        "ix_user_nudge_silences_user_type_until",
        "user_nudge_silences",
        ["user_id", "nudge_type", "silenced_until"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_user_nudge_silences_user_type_until",
        table_name="user_nudge_silences",
    )
    op.drop_table("user_nudge_silences")

    op.drop_index(
        "ix_user_nudges_source_notification_event", table_name="user_nudges"
    )
    op.drop_index("ix_user_nudges_pending", table_name="user_nudges")
    op.drop_index(
        "ix_user_nudges_user_status_created", table_name="user_nudges"
    )
    op.drop_table("user_nudges")

    op.drop_index(
        "ix_pending_confirmations_user_created",
        table_name="pending_confirmations",
    )
    op.drop_index(
        "ix_pending_confirmations_unresolved",
        table_name="pending_confirmations",
    )
    op.drop_table("pending_confirmations")
